import Head from 'next/head'
import { Eye, EyeOff, Lock, Mail } from 'react-feather'
import { useEffect, useState } from 'react'
import { register, resendOtp, verifyOtp } from '../api/auth';
import Link from 'next/link';
import OtpInput from 'react-otp-input';
import { toast } from 'react-toastify';
import { useRouter } from 'next/router';
import axios from 'axios';
import Particle from '../components/particle';
import { getCookie, getCookies } from 'cookies-next';


export default function Register() {
  const router = useRouter();
  const [otp, setOpt] = useState();
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);
  const [sendingOtp, setSendingOtp] = useState(false);

  const handleChange = (otp: any) => setOpt(otp);

  function handleSubmit(e: any)
  {
    e.preventDefault();
    setLoading(true);

    verifyOtp(otp)
    .then(({ data }: any) => {
      setLoading(false);
      toast.success(data.message);

      let selected_plan = getCookie('selected_plan');
      router.push(`plans/${selected_plan}`);
    }).catch(({ response }: any) => {
      setErrors(response?.data);
      setLoading(false);
    })
  }

  function resendOtpHandler()
  {
    setSendingOtp(true);
    resendOtp()
    .then(({ data }: any) => {
        toast.success(data.message);
        setSendingOtp(false);
    }).catch(err => setSendingOtp(false))
  }

  return (
    <>
      <Head>
        <title>CoParenting Plus - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className="container-fluid">
            <div className='bg-main h-[100vh] d-flex relative'>
                <div className='w-[430px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
                <div className='mt-5'>
                    <div className="card-top bg-[#030128] text-center p-[20px] rounded-t-[20px]">
                    <p className='text-white text-[12px] font-[400] mb-0'>Sign Up</p>
                    <p className='text-white text-[15px] font-[600] mb-0'>Verify Email</p>
                    </div>

                    <div className="card-body bg-[#F1F1F1] rounded-b-[20px] h-[72vh]">
                    <form onSubmit={handleSubmit} className='h-100  p-[50px]'>
                        <div className="form h-100 relative">
                            <img src="/img/verify.svg" className='verify-img' alt="" />
                            <p className='text-center text-[12px] pt-4 text-[#030128]'>A unique OTP has been sent to your nominated email address.</p>

                            <div className='otp my-[35px] mx-[10px]'>
                                <OtpInput
                                    value={otp}
                                    onChange={handleChange}
                                    numInputs={4}
                                    separator={<span></span>}
                                />
                                <div className='text-[12px] text-danger pt-1'>
                                    {errors?.password?.join('\n')}
                                </div>
                            </div>

                            <div className='text-[12px] text-danger pt-1 px-2'>
                                {errors?.message}
                            </div>


                        <div className='w-100 pb-5 text-center'>
                            <button disabled={loading} type='submit' className='btn-primary w-100'>
                            { loading ? 'Loading...' : 'Next' } 
                            </button>

                            <p className='text-[12px] pt-3 mb-0'><span className='text-[#030128]/[.6]'> Didn’t recieve an email OTP? </span> {sendingOtp ? <span className='text-[#586FF3]' >Sending...</span> : <span onClick={resendOtpHandler} className='text-[#586FF3] cursor-pointer'>Resend</span>}</p>
                        </div>
                        </div>
                    </form>
                    </div>

                </div>
                </div>
                
                {/* vector  */}
                <Particle/>
            </div>
        </div>
    </>
  )
}

export async function getServerSideProps({ req, res }: any) {
    let token = req.cookies.token;
    let selected_plan = req.cookies.selected_plan;

    if(token)
    {
        const data = await axios.get('/info', {
            headers: {
                'Authorization': `Bearer ${token}`
            }}
        );
        
        const { email_verified_at, active_plan, date_of_birth } = data?.data;

        if(email_verified_at && !active_plan?.length){
            if(selected_plan)
            {
                return {
                    redirect: {
                        permanent: false,
                        destination: `/plans/${selected_plan}`
                    },
                };
            }

            return {
                redirect: {
                    permanent: false,
                    destination: `/plans`
                },
            };
        }
        else if(active_plan?.length && email_verified_at && !date_of_birth)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/success'
                },
            };
        }
        else if(active_plan?.length && date_of_birth && email_verified_at)
        {
            {
                return {
                    redirect: {
                        permanent: false,
                        destination: '/profile-complete'
                    },
                };
            }
        }
    }

    return {
      props: {
  
      },
    }
}
