import Head from 'next/head'
import { useState } from 'react'
import { forgotPassword, login, resetPassword } from '../api/auth';
import { setCookie } from 'cookies-next';
import { toast } from 'react-toastify';
import { Eye, EyeOff, Lock, Mail } from 'react-feather';
import Particle from '../components/particle';
import Link from 'next/link';
import { LoadingOutlined } from '@ant-design/icons';
import { Box, Modal } from '@mui/material';

const style = {
  position: 'absolute' as 'absolute',
  top: '40%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 400,
  bgcolor: 'background.paper',
  p: 4,
  outline: 'unset'
};

export default function Login() {
  const [visible, setVisible] = useState('password');
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);
  const [loadingFor, setLoadingFor] = useState(false);
  const [loadingReset, setLoadingReset] = useState(false);
  const [modal, setModal] = useState(false);
  const [modalReset, setModalReset] = useState(false);

  function registerUser(e: any)
  {
    e.preventDefault();
    setLoading(true);
    let form = new FormData(e.target);

    login(form)
    .then(({ data }: any) => {
      setCookie('token', data.data.token);
      toast.success(data.message);
      setErrors(null);
      setLoading(false);
    }).catch(({ response }: any) => {
      setErrors(response?.data?.errors);
      setLoading(false);
    })
  }

  function onForgotPass(e: any) {
    e.preventDefault();
    setLoadingFor(true);
    let form = new FormData(e.target);
    forgotPassword(form)
    .then(res => {
      setModal(false);
      setModalReset(true);
      setLoadingFor(false);
      toast.success(res.data.message);
    }).catch(err => {
      setLoadingFor(false);
    })
  }

  function onResetPass(e: any) {
    e.preventDefault();
    setLoadingReset(true);
    let form = new FormData(e.target);
    resetPassword(form)
    .then(res => {
      toast.success(res.data.message);
      setModalReset(false);
      setLoadingReset(false);
    }).catch(err => {
      toast.error(err.response.data.message);
      setLoadingReset(false);
    })
  }

  return (
    <>
      <Head>
        <title>CoParenting Plus - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container-fluid' id="login">
        <div className='bg-main h-[100vh] d-flex relative'>
          <div className='w-[430px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
            <div className='mt-5'>
              <div className="card-top bg-[#030128] text-center p-[20px] rounded-t-[20px]">
                <p className='text-white text-[12px] font-[400] mb-0'>Sign In</p>
                <p className='text-white text-[15px] font-[600] mb-0'>Email & Password</p>
              </div>

              <div className="card-body bg-[#F1F1F1] rounded-b-[20px] h-[73vh]">
                <form onSubmit={registerUser} className='p-[50px] h-100'>
                  <div className="form d-flex flex-wrap content-space-between h-100 relative">

                    <div className='w-100'>
                      <div className='pt-3 w-100'>
                        <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Email</label>

                        <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                          <div className='my-auto mr-2'>
                            <Mail color='#6FE830' size={17}/>
                          </div>
                          <input required name='email' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Example@gmail.com' type="email" />
                        </div>
                      </div>

                      {errors?.email &&<div className='w-100 text-[12px] text-danger pt-1'>
                        {errors?.email?.join('\n')}
                      </div>}

                      <div className='mt-3 w-100'>
                        <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Password</label>

                        <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                          <div className='my-auto mr-2'>
                            <Lock color='#1d1d77e3' size={17}/>
                          </div>
                          <input required name='password' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Password' type={visible} />
                          {
                            visible === 'password' ?
                            <Eye onClick={() => visible === 'password' ? setVisible('text') : setVisible('password')} color='#00000033' size={19}/>
                            : <EyeOff onClick={() => visible === 'password' ? setVisible('text') : setVisible('password')} color='#00000033' size={19}/>
                          }
            
                        </div>
                      </div>
                      <div onClick={() =>  setModal(true)} className='mt-2 text-right text-[14px] cursor-pointer'><small>Forgot Password?</small></div>

                      <div className='text-[12px] text-danger pt-1'>
                        {errors?.password?.join('\n')}
                      </div>
                    </div>

                    
                    <div className='pt-5 pb-3 w-100 btn-div text-center self-end'>
                      <button disabled={loading} type='submit' className='btn-primary w-100'>
                          { loading ?
                              <>
                                  <LoadingOutlined className='my-auto icon mr-2'/> Loading...
                              </>
                              : 'Login' 
                          } 
                      </button>

                      <p className='text-[12px] pt-3 mb-0'><span className='text-[#030128]/[.6]'> Not a member?</span> <Link href={"register"}><span className='text-[#586FF3]'>Sign Up</span></Link></p>
                    </div>
                  </div>
                </form>
              </div>

            </div>
          </div>

          <Particle/>

          <Modal
            open={modal}
            onClose={(e) => setModal(false)}
            aria-labelledby="parent-modal-title"
            aria-describedby="parent-modal-description"
          >
            <Box sx={style}>
              <form onSubmit={onForgotPass}>
                <h4 id="parent-modal-title">Forgot Password</h4>
                <div className='pt-3 w-100'>
                  <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Email</label>

                  <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                    <div className='my-auto mr-2'>
                      <Mail color='#6FE830' size={17}/>
                    </div>
                    <input required name='email' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Example@gmail.com' type="email" />
                  </div>
                </div>

                <button disabled={loading} type='submit' className='btn-primary mt-4 w-100'>
                    { loadingFor ?
                        <>
                            <LoadingOutlined className='my-auto icon mr-2'/> 
                        </>
                        : 'Send' 
                    } 
                </button>
              </form>

            </Box>
          </Modal>

          <Modal
            open={modalReset}
            onClose={(e) => setModalReset(false)}
            aria-labelledby="parent-modal-title"
            aria-describedby="parent-modal-description"
          >
            <Box sx={style}>
              <form onSubmit={onResetPass}>
                <h4 id="parent-modal-title">Reset Password</h4>
                <div className='pt-3 w-100'>
                  <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Otp Code</label>

                  <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                    <div className='my-auto mr-2'>
                      <Mail color='#6FE830' size={17}/>
                    </div>
                    <input required name='code' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='1234' type="text" />
                  </div>
                </div>

                <div className='pt-3 w-100'>
                  <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Password</label>

                  <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                    <div className='my-auto mr-2'>
                      <Mail color='#6FE830' size={17}/>
                    </div>
                    <input required name='password' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='*********' type="password" />
                  </div>
                </div>

                <button disabled={loading} type='submit' className='btn-primary mt-4 w-100'>
                    { loadingReset ?
                        <>
                            <LoadingOutlined className='my-auto icon mr-2'/> 
                        </>
                        : 'Reset Password' 
                    } 
                </button>
              </form>

            </Box>
          </Modal>
        </div>
      </div>
    </>
  )
}
