import Head from 'next/head'
import { Calendar, File, Map, MapPin, Phone, Plus} from 'react-feather'
import { useState } from 'react'
import { userUpdate } from '../api/auth';
import { useRouter } from 'next/router';

import axios from 'axios';
import Particle from '../components/particle';
import GooglePlacesAutocomplete, { geocodeByPlaceId, getLatLng } from 'react-google-places-autocomplete';
import { LoadingOutlined } from '@ant-design/icons';

export default function Register() {
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);
  const [location, setLocation]: any  = useState(null);
  const [previewImg, setPreviewImg]: any = useState(null);
  

  const router = useRouter();

  function profileUpdate(e: any)
  {
    e.preventDefault();
    setLoading(true);
    let form = new FormData(e.target);

    if(location)
    {
        form.append('city', location.value.city);
        form.append('country', location.value.country);
        form.append('state', location.value.state);
        form.append('lat', location.value.lat);
        form.append('lon', location.value.long);
        form.append('whole_address', location.value.whole_location);
    }

    userUpdate(form)
    .then(({ data }: any) => {
      setErrors(null);
      setLoading(false);
    //   router.push('/profile-complete')
    }).catch(({ response }: any) => {
      setErrors(response?.data?.errors);
      setLoading(false);
    })
  }

  function imgChange(e: any)
  {
    const [file] = e.target.files
    if(file)
    {
       setPreviewImg(URL.createObjectURL(file));
    }
  }

  const getLocationData = (location: any) => {
    if (location) {
      const {
        value: { place_id },
      } = location;

      return (async () => {
        if (!place_id) return;

        const results = await geocodeByPlaceId(place_id);
        if (!results) {
          return;
        }

        const latLong = await getLatLng(results[0]);
        const { address_components, formatted_address } = results[0];

        let city, state, country, postalCode;
        for (let i = 0; i < address_components.length; i++) {
          for (let j = 0; j < address_components[i].types.length; j++) {
            switch (address_components[i].types[j]) {
              case "locality":
                city = address_components[i].long_name;
                break;
              case "administrative_area_level_1":
                state = address_components[i].long_name;
                break;
              case "country":
                country = address_components[i].long_name;
                break;
              case "postal_code":
                postalCode = address_components[i].long_name;
                break;
              default:
                break;
            }
          }
        }

        setLocation({
          ...location,
          value: {
            ...location.value,
            country: country,
            city: city,
            state: state,
            lat: latLong.lat,
            long: latLong.lng,
            whole_location: location.label
          },
        });
      })();
    }
  };

  return (
    <>
      <Head>
        <title>CoParenting Plus - Profile Update</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <div className="container-fluid profile">
            <div className='bg-main h-[100vh] d-flex relative'>
                <div className='w-[450px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
                <div className='mt-5'>
                    <div className="card-top bg-[#030128] text-center p-[20px] rounded-t-[20px]">
                    <p className='text-white text-[11px] font-[400] mb-0'>Profile Creation</p>
                    <p className='text-white text-[15px] font-[600] mb-0'>Profile Details</p>
                    </div>

                    <div className="card-body bg-[#F1F1F1] h-[78vh] rounded-b-[20px]">
                    <form onSubmit={profileUpdate} className='h-100 p-[40px]' encType="multipart/form-data">
                        <div className="form h-100 relative">

                            <div className='d-flex border-[#03012826] border-[1px] border-dashed relative w-[100px] h-[100px] bg-white rounded-[10px] text-center m-auto mb-4'>
                                <img className='absolute rounded-[10px] left-0 right-0 top-0 bottom-0' src={previewImg} alt="" />
                                <input onChange={(e) => imgChange(e)} className='absolute opacity-[0] left-0 right-0 top-0 bottom-0' type="file" name="profile_picture" accept='.png,.jpeg,.jpg' />

                                <div className='m-auto pt-3'>
                                    <Plus className='m-auto' color='#1D1D77'/>
                            
                                    <div className='text-center pt-1 leading-[15px]'>
                                        <p className='mb-0 text-[#1D1D77]/[.4] font-[500] text-[13px]'>
                                            Upload
                                        </p>
                                        <div className='font-[300] text-[13px] text-[#1D1D77]/[.4]'> <p>(Optional)</p></div>
                                    </div>
                                </div>
                            </div>
                        
                            <div className='d-flex gap-3 pt-2'>
                                <div className='w-100'>
                                    <label htmlFor="" className='text-[13px] font-[500] mb-[3px]'>First Name</label>

                                    <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                                    <input required name='first_name' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='John' type="text" />
                                    </div>
                                </div>
                                <div className='w-100'>
                                    <label htmlFor="" className='text-[13px] font-[500] mb-[3px]'>Last Name</label>

                                    <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                                    <input required name='last_name' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Doe' type="text" />
                                    </div>
                                </div>
                            </div>

                        <div className='text-[12px] text-danger pt-1'>
                            {errors?.first_name?.join('\n')}
                        </div>

                        <div className="d-flex gap-3 mt-1">
                            <div className='w-100'>
                                <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Address</label>
                                <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] px-[13px] py-[3.78px] rounded-[10px]'>
                                    <div className='my-auto mr-2 relative z-[99]'>
                                        <MapPin color='#1d1d77e3' size={17}/>
                                    </div>
                                    <div className='w-100 mx-[-10px] autocomplete-select'>
                                        <GooglePlacesAutocomplete
                                            autocompletionRequest={{
                                                componentRestrictions: {
                                                    country: ['au'],
                                                }
                                            }}
                                            apiKey={'AIzaSyCqwYRMTR5bxU2eKddDySd98om88fYWqyY'}
                                            selectProps={{
                                                placeholder: 'Select Location',
                                                noOptionsMessage: (_: any) => "Enter location...",
                                                onChange: (e: any) => getLocationData(e)
                                            }}
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* <div className='mt-2 w-100'>
                                <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>State</label>

                                <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                                <div className='my-auto mr-2'>
                                    <Map color='#1d1d77e3' size={17}/>
                                </div>
                                <select name="state" defaultValue={""} className='w-100  focus-visible:outline-none text-[14px]'>
                                    <option disabled value={""}>Select State</option>
                                    {
                                        ['VIC', 'NSW', 'SA', 'QLD', 'TAS', 'WA'].map((res) => (
                                            <option value={res} key={res}>{res}</option>
                                        ))
                                    }
                                </select>
                                </div>
                            </div>

                            <div className='mt-2 w-100'>
                                <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Address</label>

                                <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                                <div className='my-auto mr-2'>
                                    <MapPin color='#1d1d77e3' size={17}/>
                                </div>
                                <input required name='address' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='address' type="text" />
                                </div>
                            </div> */}
                        </div>

                        <div className='text-[12px] text-danger pt-1'>
                            {errors?.whole_address?.join('\n')}
                        </div>

                        <div className='mt-2'>
                            <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Phone</label>

                            <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                            <div className='my-auto mr-2'>
                                <Phone color='#1d1d77e3' size={17}/>
                            </div>
                            <input required name='phone' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Phone Number' type={"tel"} />
                            </div>
                        </div>

                        <div className='d-flex gap-3'>
                            <div className='mt-2 w-100'>
                                <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Driver License</label>

                                <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                                <div className='my-auto mr-2'>
                                    <File color='#1d1d77e3' size={17}/>
                                </div>
                                <input required minLength={11} maxLength={11} name='driver_license' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Driver License' type="text" />
                                </div>
                            </div>

                            <div className='mt-2 w-100'>
                                <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Date Of Birth</label>

                                <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                                <div className='my-auto mr-2'>
                                    <Calendar color='#1d1d77e3' size={17}/>
                                </div>
                                <input required max={new Date().toLocaleDateString('en-ca')} name='date_of_birth' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Date Of Birth' type="date" />
                                </div>
                            </div>
                        </div>

                        <div className='text-[12px] text-danger pt-1'>
                            {errors?.driver_license?.join('\n')}
                        </div>

                        <div className='text-[12px] text-danger pt-1'>
                            {errors?.password?.join('\n')}
                        </div>

                            <div className='mt-5 pb-4 w-100'>
                                <button disabled={loading} type='submit' className='btn-primary w-100'>
                                        { loading ?
                                            <>
                                                <LoadingOutlined className='my-auto icon mr-2'/> Loading...
                                            </>
                                            : 'Complete' 
                                        } 
                                </button>
                            </div>
                        </div>
                    </form>
                    </div>

                </div>
                </div>
                
                {/* vector  */}
                <Particle/>
            </div>
        </div>
    </>
  )
}

export async function getServerSideProps({ req, res }: any) {
    let token = req.cookies.token;

    if(token)
    {
        const data = await axios.get('/info', {
            headers: {
                'Authorization': `Bearer ${token}`
            }}
        );
        
        const { email_verified_at, active_plan, date_of_birth } = data?.data;

        if(email_verified_at && active_plan && date_of_birth)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/profile-complete'
                },
            };
        }

        if(email_verified_at && !active_plan)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/plans'
                },
            };
        }

        if(!email_verified_at && !active_plan)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/verify'
                },
            };
        }
    }

    return {
      props: {
  
      },
    }
}
