import Head from 'next/head'
import { Eye, EyeOff, Lock, Mail } from 'react-feather'
import { useEffect, useState } from 'react'
import { register, instance } from '../api/auth';
import useSWR from 'swr'
import { useRouter } from 'next/router';
import axios from 'axios';
import { setCookie } from 'cookies-next';
import { toast } from 'react-toastify';
import Particle from '../components/particle';
import Link from 'next/link';

export default function Register() {
  const router = useRouter();
  const [visible, setVisible] = useState('password');
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);

  function registerUser(e: any)
  {
    e.preventDefault();
    setLoading(true);
    let form = new FormData(e.target);

    register(form)
    .then(({ data }: any) => {
        setCookie('token', data.data.token);
        toast.success(data.message);
        setLoading(false);
        router.push('/verify');
    }).catch(({ response }: any) => {
      setErrors(response?.data?.errors);
      setLoading(false);
    })
  }

  return (
    <>
      <Head>
        <title>CoParenting Plus - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className='container-fluid'>
            <div className='bg-main h-[100vh] d-flex relative'>
                <div className='w-[430px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
                <div className='mt-5'>
                    <div className="card-top bg-[#030128] text-center p-[20px] rounded-t-[20px]">
                    <p className='text-white text-[12px] font-[400] mb-0'>Sign Up</p>
                    <p className='text-white text-[15px] font-[600] mb-0'>Email & Password</p>
                    </div>

                    <div className="card-body bg-[#F1F1F1] rounded-b-[20px] h-[73vh]">
                        <form onSubmit={registerUser} className='h-100 p-[50px]'>
                            <div className="form h-100 relative d-flex flex-wrap content-between">
                                <div className='w-100'>
                                    <div className='pt-3'>
                                        <label htmlFor="" className='text-[13px] font-[500] mb-[3px]'>Email</label>

                                        <div className='w-100 d-flex form-gr border-[1px] border-[#6FE830] p-[13px] rounded-[10px]'>
                                        <div className='my-auto mr-2'>
                                            <Mail color='#6FE830' size={17}/>
                                        </div>
                                        <input required name='email' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Example@gmail.com' type="text" />
                                        </div>
                                    </div>

                                    {errors?.email && <div className='text-[12px] text-danger pt-1'>
                                        {errors?.email?.join('\n')}
                                    </div>}

                                    <div className='mt-3'>
                                        <label htmlFor="" className='text-[13px] text-[#030128] font-[500] mb-[3px]'>Password</label>

                                        <div className='w-100 d-flex bg-white border-[1px] border-[#00000033] p-[13px] rounded-[10px]'>
                                        <div className='my-auto mr-2'>
                                            <Lock color='#1d1d77e3' size={17}/>
                                        </div>
                                        <input required name='password' className='bg-[transparent] w-100 text-[13px] focus-visible:outline-none' placeholder='Password' type={visible} />
                                        {
                                            visible === 'password' ?
                                            <Eye onClick={() => visible === 'password' ? setVisible('text') : setVisible('password')} color='#00000033' size={19}/>
                                            : <EyeOff onClick={() => visible === 'password' ? setVisible('text') : setVisible('password')} color='#00000033' size={19}/>
                                        }
                            
                                        </div>
                                    </div>

                                    <div className='text-[12px] text-danger pt-1'>
                                        {errors?.password?.join('\n')}
                                    </div>

                                </div>

                                <div className='pt-5 pb-3 w-100 btn-div text-center'>
                                    <button disabled={loading} type='submit' className='btn-primary w-100'>
                                        { loading ? 'Loading...' : 'Next' } 
                                    </button>

                                    <p className='text-[13px] pt-3 mb-0'><span className='text-[#030128]/[]'> Already a member?</span> <Link href={"login"}><span className='text-[#586FF3]'>Sign In</span></Link></p>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                </div>
                
                
                {/* vector  */}
                <Particle/>
            </div>
        </div>
    </>
  )
}


export async function getServerSideProps({ req, res }: any) {
    let token = req.cookies.token;

    if(token)
    {
        const data = await axios.get('/info', {
            headers: {
                'Authorization': `Bearer ${token}`
            }}
        );
        
        const { email_verified_at, active_plan, date_of_birth } = data?.data;

        if(!email_verified_at)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/verify'
                },
            };
        }

        if(email_verified_at && !active_plan.length){        
            return {
                redirect: {
                    permanent: false,
                    destination: '/plans'
                },
            };
        };
        
        if(active_plan.length && email_verified_at && !date_of_birth)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/success'
                },
            };
        }
        
        if(active_plan.length && date_of_birth && email_verified_at) 
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/profile-complete'
                },
            };
        }
    }

    return {
      props: {},
    }
}