import Head from 'next/head'
import { useState } from 'react'
import { login } from './api/auth';
import { setCookie } from 'cookies-next';
import { toast } from 'react-toastify';
import Register from './register';
import Plans from './plans';

export default function Home() {
  const [visible, setVisible] = useState('password');
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);

  function registerUser(e: any)
  {
    e.preventDefault();
    setLoading(true);
    let form = new FormData(e.target);

    login(form)
    .then(({ data }: any) => {
      setCookie('token', data.data.token);
      toast.success(data.message);
      setErrors(null);
      setLoading(false);
    }).catch(({ response }: any) => {
      setErrors(response?.data?.errors);
      setLoading(false);
    })
  }

  return (
    <>
      <Head>
        <title>CoParenting Plus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Plans/>
    </>
  )
}
