import Head from 'next/head'
import { useState } from 'react'
import { login } from './api/auth';
import { setCookie } from 'cookies-next';
import { toast } from 'react-toastify';
import Register from './register';
import Plans from './plans';

export default function Home() {
  return (
    <>
      <Head>
        <title>CoParenting Plus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Plans/>
    </>
  )
}

