import Head from 'next/head'
import React, { useEffect, useRef, useState } from 'react'
import { register, instance, subscription } from '../api/auth';
import useSWR from 'swr'
import { useRouter } from 'next/router';
import {loadStripe} from '@stripe/stripe-js';
import {
  CardElement,
  Elements,
  useStripe,
  useElements,
} from '@stripe/react-stripe-js';
import { toast } from 'react-toastify';
import Particle from '../components/particle';
import Skeleton from '../components/skeleton';

const CheckoutForm = ({ intent }: any) => {
    const router = useRouter();
    const stripe: any = useStripe();
    const elements = useElements();

    const [loading, setLoading] = useState(false);

    const { query } = useRouter();
  
    const handleSubmit = async (event: any) => {
        event.preventDefault();
        setLoading(true);
  
        if (elements == null) {
            toast.error('Something went wrong!');
            return;
        }
        const {setupIntent, error}:any = await stripe.confirmCardSetup( intent?.data?.client_secret, {
            payment_method: {
            card: elements.getElement(CardElement)
            }
        });

        if (error) {
            toast.error(error);
            setLoading(false);
        } else {
            subscription(query.id, setupIntent.payment_method)
            .then(res => {
                toast.error(res.data.message);
                setLoading(false);
                router.push('/success');
            })
        }
    };
  
    return (
      <form onSubmit={handleSubmit}>
        <div className='bg-[#fff] p-3 rounded-[10px] mb-4'>
            <CardElement />
        </div>
        <button className='btn-primary w-100 mt-5 mb-4' type="submit" disabled={!stripe || !elements}>
          {loading ? 'Loading...' : 'Pay'}
        </button>
      </form>
    );
  };

const stripePromise = loadStripe('pk_test_51MRuPFJloZqbdR1uUvOKMgECphmJ2kL5NVzwuEaRcb2x3F5QLZSmSRhrkVn779nPKpZGL5P7RkiafILpN8sbnT7O00eSjU0xl3');


export default function Plans() {
  let refPlan: any = useRef();
  const { query }: any = useRouter();
  const [selectedPlan, setSelectedPlan] = useState(null);
  const [selectedFeature, setSelectedFeature] = useState<any>(null);

  const fetcher = (url: any) => instance(url);
  const { data, error }: any = useSWR('plans', fetcher);

  const { data:intent, error:errorIntent }: any = useSWR('get-intent', fetcher);

  useEffect(() => {
    if(query?.id) setSelectedPlan(query?.id);
    if(data){
        setTimeout(() => {
            refPlan?.current?.click()
        }, 50)
    };
  }, [query?.id, data])

  return (
    <>
      <Head>
        <title>CoParenting Plus - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">
        <div className='bg-main h-[100vh] d-flex relative'>
            <div className='w-[370px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
            <div>
                <div className="card-body no-header bg-[#F1F1F1] rounded-[20px] h-[80vh] d-flex flex-wrap content-space-between">
    
                    <div className='z-[0]'>
                        <img src="/img/plan.svg" className='absolute left-0 w-[100%] right-0 rounded-t-[20px]' alt="" />
                    </div>

                    <div className='w-100'>

                        <div className='d-flex gap-2 pt-[240px] p-[30px] relative z-[99]'>
                            {!data ? <Skeleton/> :
                                data.data.map((res:any, key: number) => (
                                    <React.Fragment key={key}>
                                        <div className='w-100'>
                                            <div ref={selectedPlan == res.id ? refPlan : null} onClick={() => {setSelectedPlan(res.id);setSelectedFeature(res.features)}} className={`${selectedPlan == res.id && 'selected'} cursor-pointer bg-[#FFFFFF80] d-flex h-[90px] border-[#03012826] border-[1px] rounded-[10px]`}>
                                                <div className='m-auto text-center'> 
                                                    <p className='mb-0 text-[#030128] text-[14px] font-[600] capitalize'> { res.price === 0 ? 'Free' : res.intervel}</p>
                                                    <p className='mb-0 text-[19px] font-[700]'>${res.price}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </React.Fragment>
                                ))
                            }
                        </div>

                        {selectedFeature && <div className='px-[35px] plan-list z-[999] relative'>
                            {
                                selectedFeature?.map((res: any, key: number) => (
                                    <li className='text-[14px] d-flex mb-2' key={key}>
                                        <img src="/img/tick.svg" className='w-[16px] mr-2' alt="" />
                                        {res.description}
                                    </li>
                                ))
                            }
                        </div>}

                        <div className='bg-fade absolute top-[47%] left-0 right-0 bottom-0 rounded-b-[20px]'>

                        </div>

                        </div>

                    {intent && <div className='px-[30px] py-3 relative w-100'>
                        <Elements stripe={stripePromise}>
                            <CheckoutForm intent={intent} />
                        </Elements>
                    </div>}

                </div>

            </div>
            </div>
            
            {/* vector  */}
            <Particle/>
        </div>
      </div>
    </>
  )
}
