import Head from 'next/head'
import React, { useEffect, useRef, useState } from 'react'
import { register, instance } from '../api/auth';
import useSWR from 'swr'
import Link from 'next/link';
import Particle from '../components/particle';
import Skeleton from '../components/skeleton';
import { getCookie, setCookie } from 'cookies-next';

export default function Plans() {
  let refPlan: any = useRef();
  let token = getCookie('token');
  const [selectedPlan, setSelectedPlan]: any = useState(null);
  const [selectedFeature, setSelectedFeature] = useState<any>(null);

  const { data, error }: any = useSWR('plans', instance);

  useEffect(() => {
    setSelectedPlan(3);
    if(data){
        setTimeout(() => {
            refPlan?.current?.click()
        }, 50)
    };
  }, [data]);

  useEffect(() => {
    if(selectedPlan)
    {   
        setCookie('selected_plan', selectedPlan);
    }
  }, [selectedPlan]);

  return (
    <>
        <Head>
            <title>CoParenting Plus - Plans</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container-fluid">
            <div className='bg-main h-[100vh] d-flex relative'>
            <div className='w-[370px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
            <div>
                <div className="card-body no-header bg-[#F1F1F1] rounded-[20px] h-[80vh] d-flex flex-wrap content-space-between">
                    <div className='z-[0]'>
                        <img src="/img/plan.svg" className='absolute left-0 w-[100%] right-0 rounded-t-[20px]' alt="" />
                    </div>

                    <div className='w-100'>

                        <div className='d-flex gap-2 pt-[240px] p-[30px] relative z-[99]'>
                            {!data ? <Skeleton/> :
                                data?.data.map((res:any, key: number) => (
                                    <React.Fragment key={key}>
                                        <div className='w-100'>
                                            <div ref={refPlan} onClick={() => {setSelectedPlan(res.id);setSelectedFeature(res.features)}} className={`${selectedPlan === res.id && 'selected'} cursor-pointer bg-[#FFFFFF80] d-flex h-[90px] border-[#03012826] border-[1px] rounded-[10px]`}>
                                                <div className='m-auto text-center'> 
                                                    <p className='mb-0 text-[#030128] text-[14px] font-[600] capitalize'> { res.price === 0 ? 'Free' : res.intervel}</p>
                                                    <p className='mb-0 text-[19px] font-[700]'>${res.price}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </React.Fragment>
                                ))
                            }
                        </div>

                        {selectedFeature && <div className='px-[35px] plan-list z-[999] relative'>
                            {
                                selectedFeature?.map((res: any, key: number) => (
                                    <li className='text-[14px] d-flex mb-2' key={key}>
                                        <img src="/img/tick.svg" className='w-[16px] mr-2' alt="" />
                                        {res.description}
                                    </li>
                                ))
                            }
                        </div>}

                        <div className='bg-fade absolute top-[47%] left-0 right-0 bottom-0 rounded-b-[20px]'>

                        </div>

                    </div>

                    <div className='d-flex flex-wrap pt-5 px-[30px] w-100 self-end pb-5 btn-div'>
                        <Link href={token ? `/plan/${selectedPlan}` : '/register'} className="w-100">
                            <button disabled={selectedPlan === null ? true : false} type='submit' className='btn-primary w-100'>
                                { !selectedPlan ? 'Select Plan' : 'Subscribe' } 
                            </button>
                        </Link>
                    </div>
                </div>

            </div>
            </div>
            
            
            {/* vector  */}
            <Particle/>
            </div>
        </div>
    </>
  )
}