import Head from 'next/head'
import { Eye, EyeOff, Lock, Mail } from 'react-feather'
import { useEffect, useState } from 'react'
import { register, instance } from '../api/auth';
import useSWR from 'swr'
import { useRouter } from 'next/router';
import Link from 'next/link';
import axios from 'axios';
import Particle from '../components/particle';

export default function Success() {
  const [visible, setVisible] = useState('password');
  const [errors, setErrors] = useState<any>();
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const { data, error } = useSWR('/', instance);
 
  useEffect(() => {
    if(data?.data?.email_verified_at)
    {
     
    }
    
    if(error?.response?.data?.message === 'email_not_verified')
    {
        router.push('/verify')
    }
  }, [error?.response?.data?.message])

  return (
    <>
      <Head>
        <title>CoParenting Plus - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">
        <div className='bg-main h-[100vh] d-flex relative'>
            <div className='w-[370px] form-outer my-auto ml-auto mr-[130px] relative z-[999]'>
            <div className='mt-5'>
                <div className="card-body no-header bg-[#F1F1F1] h-[77vh] rounded-[20px] bg-right">

                    <div className=''>
                        <img src="/img/success.svg" alt="" />
                    </div>

                    <form className='mt-[-240px] px-[40px]'>
                        <div className="form h-100 relative">
                            <div className='text-center my-5 px-5'>
                                <h2 className='text-[#030128] text-[24px] font-[700]'>Congrats</h2>
                                <p className='text-[12px] pt-[10px] text-[#030128]/[.6]'>You have successfully added & verified your account</p>
                            </div>

                            <div className='btn-div without-secline'>
                                <Link href={'/profile-detail'} className="relative z-[9999]">
                                    <button type='submit' className='btn-primary mt-5 w-100'>
                                        { loading ? 'Loading...' : 'Customise Profile' } 
                                    </button>
                                </Link>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
            </div>
            
            {/* vector  */}
            <Particle/>
        </div>
      </div>   
    </>
  )
}

export async function getServerSideProps({ req, res }: any) {
    let token = req.cookies.token;

    if(token)
    {
        const data = await axios.get('/info', {
            headers: {
                'Authorization': `Bearer ${token}`
            }}
        );
        
        const { email_verified_at, active_plan, date_of_birth } = data?.data;

        if(email_verified_at && active_plan && date_of_birth)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/profile-complete'
                },
            };
        }

        if(email_verified_at && !active_plan && !date_of_birth)
        {
            return {
                redirect: {
                    permanent: false,
                    destination: '/plans'
                },
            };
        }
    }

    return {
      props: {
  
      },
    }
}
